In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv("df6.csv", sep="\t")

In [6]:
# On paramétrise notre display function pour avoir toutes les variables
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,Valeur fonciere,Code postal,Commune,Code commune,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,exterieur,year,month,code_postal,nom_commune,nom_departement,nom_region,latitude,longitude,code_departement,pop_active,salaire_moyen,nb_etab_elem
0,0,90000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Maison,150.0,3,347.0,1.0,2018,1,1380,SAINT-CYR-SUR-MENTHON,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,1,320682.0,15.336249,405
1,1,7300.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,344.0,1.0,2018,1,1380,SAINT-CYR-SUR-MENTHON,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,1,320682.0,15.336249,405
2,2,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,210.0,1.0,2018,1,1380,SAINT-CYR-SUR-MENTHON,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,1,320682.0,15.336249,405
3,3,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,798.0,1.0,2018,1,1380,SAINT-CYR-SUR-MENTHON,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,1,320682.0,15.336249,405
4,4,69000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,979.0,1.0,2018,2,1380,SAINT-CYR-SUR-MENTHON,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,1,320682.0,15.336249,405

In [7]:
df.drop(columns=["nom_commune", "code_postal", "code_departement"], inplace=True)

In [8]:
df.head()

,Unnamed: 0,Valeur fonciere,Code postal,Commune,Code commune,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,exterieur,year,month,nom_departement,nom_region,latitude,longitude,pop_active,salaire_moyen,nb_etab_elem
0,0,90000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Maison,150.0,3,347.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
1,1,7300.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,344.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
2,2,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,210.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
3,3,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,798.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
4,4,69000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,979.0,1.0,2018,2,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405

In [9]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [10]:
df.head()

,Valeur fonciere,Code postal,Commune,Code commune,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,exterieur,year,month,nom_departement,nom_region,latitude,longitude,pop_active,salaire_moyen,nb_etab_elem
0,90000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Maison,150.0,3,347.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
1,7300.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,344.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
2,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,210.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
3,60000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,798.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
4,69000.0,1380.0,SAINT-CYR-SUR-MENTHON,343,0,Autres,0.0,0,979.0,1.0,2018,2,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405

In [11]:
df.drop(columns=["Code postal", "Commune", "Code commune"], inplace=True)

In [12]:
df.head()

,Valeur fonciere,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,exterieur,year,month,nom_departement,nom_region,latitude,longitude,pop_active,salaire_moyen,nb_etab_elem
0,90000.0,0,Maison,150.0,3,347.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
1,7300.0,0,Autres,0.0,0,344.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
2,60000.0,0,Autres,0.0,0,210.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
3,60000.0,0,Autres,0.0,0,798.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405
4,69000.0,0,Autres,0.0,0,979.0,1.0,2018,2,Ain,Auvergne-Rhône-Alpes,46.275401,4.967571,320682.0,15.336249,405

In [13]:
df.drop(columns=["latitude", "longitude"], inplace=True)

In [14]:
df.head()

,Valeur fonciere,Nombre de lots,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,exterieur,year,month,nom_departement,nom_region,pop_active,salaire_moyen,nb_etab_elem
0,90000.0,0,Maison,150.0,3,347.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,320682.0,15.336249,405
1,7300.0,0,Autres,0.0,0,344.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,320682.0,15.336249,405
2,60000.0,0,Autres,0.0,0,210.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,320682.0,15.336249,405
3,60000.0,0,Autres,0.0,0,798.0,1.0,2018,1,Ain,Auvergne-Rhône-Alpes,320682.0,15.336249,405
4,69000.0,0,Autres,0.0,0,979.0,1.0,2018,2,Ain,Auvergne-Rhône-Alpes,320682.0,15.336249,405